# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-20 02:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 20, 2, 45, 45, 726710, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 2, 45, 45, 726710, tzinfo=utc)),
        ),
    ]
